### ISSUE TITLE
留个邮箱吧，方便联系讲一些问题

### ISSUE THREAD

**Issue by AM-young-fun** [liuxuan30/Xuan-VIM#1]
你那个图表比我了解的多，有问题先问问你好了。

**Comment by liuxuan30** [comment]
要不还是发github或者SO? 基本我休息的时候会看一眼, 平时很忙..都是抽空看一眼..效率应该差不多的,给我发邮箱可能还更慢... anyway liuxuan30@gmail.com,不过我倾向于还是发github或者SO吧, 至少很多人都会回,我一个人时间有限,难免回复的晚
